export const starType = {
  constellation: '星座',
  blood_type: '血型',
  birth_place: '出生地',
  height: '身高',
  weight: '体重',
  nation: '民族',
  citizenship: '国籍',
  school: '毕业学校',
  company: '公司',
  imdb: 'imdb编号',
  website: '官方网站',
  url: '引用链接'
}

export const anime = [
  '原作//Original Creator/Original Work',
  '总导演/総監督/Chief Director',
  '导演/監督 シリーズ監督/Director/Direction',
  '脚本/シナリオ/Script/Screenplay',
  '分镜/コンテ  ストーリーボード  画コンテ  絵コンテ/Storyboard',
  '演出//Episode Director',
  '音乐/楽曲  音楽/Music',
  '人物原案/キャラ原案/Original Character Design',
  '人物设定/キャラ設定/Character Design',
  '分镜构图/レイアウト/Layout',
  '系列构成/シナリオディレクター  構成  シリーズ構成  脚本構成/Series Composition',
  '副导演/助監督/Assistant director',
  '美术监督/アートディレクション 背景監督/Art Direction',
  '美术设计/美術設定/Art Design',
  '色彩设计/色彩設定/Color Design',
  '总作画监督/チーフ作画監督/Chief Animation Director',
  '作画监督/作監 アニメーション演出/Animation Direction',
  '机械作画监督/メカニック作監/Mechanical Animation Direction',
  '动作作画监督/アクション作画監督/Action Animation Direction',
  '机械设定/メカニック設定/Mechanical Design',
  '摄影监督/撮影監督/Director of Photography',
  'CG 导演/CG 監督/CG Director',
  '监修/シリーズ監修 スーパーバイザー/Supervision/Supervisor',
  '道具设计/プロップデザイン/Prop Design',
  '原画/作画 原画/Key Animation',
  '第二原画/原画協力/2nd Key Animation',
  '动画检查/動画チェック/Animation Check',
  '制作/製作 製作スタジオ/Production',
  '动画制作/アニメーション制作 アニメ制作 アニメーション/Animation Work',
  'OP・ED 分镜/OP・ED 分鏡/OP ED',
  '音乐制作/楽曲制作 音楽制作/Music Work',
  '助理制片人/協力プロデューサー/Assistant Producer',
  '/アソシエイトプロデューサー/Associate Producer',
  '背景美术/背景/Background Art',
  '色彩指定//Color Setting',
  '数码绘图//Digital Paint',
  '3DCG//3DCG',
  '制作管理/制作マネージャー 制作担当 制作班長/Production Manager',
  '剪辑/編集/Editing',
  '原案//Original Plan',
  '主题歌编曲//Theme Song Arrangement',
  '主题歌作曲//Theme Song Composition',
  '主题歌作词//Theme Song Lyrics',
  '主题歌演出//Theme Song Performance',
  '插入歌演出//Inserted Song Performance',
  '企画/プランニング  企画開発/Planning',
  '/企画プロデューサー  企画営業プロデューサー/Planning Producer',
  '宣传/パブリシティ  宣伝  広告宣伝  番組宣伝  製作宣伝/Publicity',
  '录音/録音/Recording',
  '录音助理/録音アシスタント  録音助手/Recording Assistant',
  '系列监督//Series Production Director',
  '製作//Production',
  '设定/設定/Setting',
  '音响监督//Sound Director',
  '音响/音響/Sound',
  '音效/音響効果/Sound Effects',
  '特效/視覚効果/Special Effects',
  '配音监督//ADR Director',
  '联合导演//Co-Director',
  '背景设定/基本設定  場面設定  場面設計  設定/Setting',
  '补间动画/動画/In-Between Animation',
  '执行制片人/製作総指揮/Executive Producer',
  '助理制片人/協力プロデューサー/Assistant Producer',
  '制片人/プロデュース  プロデューサー/Producer',
  '助理录音师//Assistant Engineer',
  '助理制片协调//Assistant Production Coordinat',
  '演员监督/キャスティングコーディネーター監督/Casting Director',
  '总制片/チーフプロデューサー  チーフ制作  総合プロデューサー/Chief Producer',
  '联合制片人//Co-Producer',
  '台词编辑/台詞編集/Dialogue Editing',
  '后期制片协调/ポストプロダクション協力/Post-Production Assistant',
  '制作助手/制作アシスタント 制作補佐 製作補/Production Assistant',
  '制作协调/制作コーディネーター/Production Coordination',
  '制作协力/制作協力 / 作品協力/Work Assistance',
  '友情協力/特别鸣谢/Special Thanks'
]

export const real = [
  '原作//creator',
  '导演//director',
  '创意总监//creative director',
  '编剧//writer',
  '音乐//composer',
  '执行制片人/製作総指揮/executive producer',
  '共同执行制作//co exec ',
  '制片人/制作人/プロデューサー/producer',
  '监制//supervising producer',
  '副制作人/制作顾问//consulting producer',
  '故事//story',
  '编审//story editor',
  '剪辑//editor',
  '摄影//cinematography',
  '主题歌演出//Theme Song Performance',
  '主演//Actor',
  '配角//Supporting Actor',
  '制作/製作 製作スタジオ/Production'
]

export const music = [
  '艺术家//',
  '制作人//',
  '作曲//',
  '作词//Lyric',
  '编曲//Arrange',
  '插图//',
  '录音//',
  '厂牌//Label',
  '原作//Original Creator/Original Work',
  '脚本/シナリオ/Scenario'
]

export const book = [
  '原作//Original Creator/Original Work',
  '作者//',
  '/作画/',
  '插图/イラスト/',
  '/出版社/',
  '连载杂志/掲載誌/',
  '译者//',
  '客串/ゲスト/guest',
  '人物原案/キャラクター原案/Original Character Design'
]

export const game = [
  '开发/開発元/developer',
  '发行/発売元/publisher',
  '遊戲設計師/ゲームクリエイター/game designer',
  '原作//',
  '导演/監督 演出 シリーズ監督/Director/Direction',
  '制作人/プロデューサー/Producer',
  '企画//',
  '监修/監修/',
  '剧本/腳本/',
  '系列构成/シリーズ構成/',
  '作画监督/作画監督/',
  '原画//',
  '人物设定/キャラ設定 キャラクターデザイン/Character Design',
  '机械设定/メカニック設定/Mechanical Design',
  '美工/美術/',
  'CG监修/CG監修/',
  'SD原画//',
  '背景//',
  '音响监督//Sound Director',
  '音乐/音楽/',
  '程序/プログラム/Program',
  '动画制作/アニメーション制作 アニメ制作 アニメーション/Animation Work',
  '动画监督/アニメーション監督/',
  '动画剧本/アニメーション脚本/',
  '制作总指挥//',
  'QC//QC',
  '关卡设计//',
  '主题歌作曲//Theme Song Composition',
  '主题歌作词//Theme Song Lyrics',
  '主题歌演出//Theme Song Performance',
  '插入歌演出//Inserted Song Performance',
  '协力/協力/'
]
